### ISSUE TITLE
numatop fails to build on i386 arches

### ISSUE THREAD

**Issue by ColinIanKing** [intel/numatop#46]
Older versions of numatop used to build on i386, the newer 2.1 version will not. See end of the build log below:

```
$ make
make  all-am
make[1]: Entering directory '/home/king/tmp/numatop'
depbase=`echo common/os/map.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/map.lo -MD -MP -MF $depbase.Tpo -c -o common/os/map.lo common/os/map.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/map.lo -MD -MP -MF common/os/.deps/map.Tpo -c common/os/map.c  -fPIC -DPIC -o common/os/.libs/map.o
common/os/map.c: In function ‘numa_map_update’:
common/os/map.c:325:41: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   if ((entry = numa_entry_add(numa_map, (uint64_t)(addr_arr[i]),
                                         ^
common/os/map.c:335:24: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    (entry->end_addr == (uint64_t)(addr_arr[j]))) {
                        ^
common/os/map.c:338:42: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    if ((entry = numa_entry_add(numa_map, (uint64_t)(addr_arr[j]),
                                          ^
common/os/map.c: In function ‘map_map2numa’:
common/os/map.c:362:18: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
    addr_arr[i] = (void *)(map_entry->start_addr +
                  ^
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/map.lo -MD -MP -MF common/os/.deps/map.Tpo -c common/os/map.c -o common/os/map.o >/dev/null 2>&1
depbase=`echo common/os/node.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/node.lo -MD -MP -MF $depbase.Tpo -c -o common/os/node.lo common/os/node.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/node.lo -MD -MP -MF common/os/.deps/node.Tpo -c common/os/node.c  -fPIC -DPIC -o common/os/.libs/node.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/node.lo -MD -MP -MF common/os/.deps/node.Tpo -c common/os/node.c -o common/os/node.o >/dev/null 2>&1
depbase=`echo common/os/os_cmd.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/os_cmd.lo -MD -MP -MF $depbase.Tpo -c -o common/os/os_cmd.lo common/os/os_cmd.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/os_cmd.lo -MD -MP -MF common/os/.deps/os_cmd.Tpo -c common/os/os_cmd.c  -fPIC -DPIC -o common/os/.libs/os_cmd.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/os_cmd.lo -MD -MP -MF common/os/.deps/os_cmd.Tpo -c common/os/os_cmd.c -o common/os/os_cmd.o >/dev/null 2>&1
depbase=`echo common/os/os_page.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/os_page.lo -MD -MP -MF $depbase.Tpo -c -o common/os/os_page.lo common/os/os_page.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/os_page.lo -MD -MP -MF common/os/.deps/os_page.Tpo -c common/os/os_page.c  -fPIC -DPIC -o common/os/.libs/os_page.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/os_page.lo -MD -MP -MF common/os/.deps/os_page.Tpo -c common/os/os_page.c -o common/os/os_page.o >/dev/null 2>&1
depbase=`echo common/os/os_perf.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/os_perf.lo -MD -MP -MF $depbase.Tpo -c -o common/os/os_perf.lo common/os/os_perf.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/os_perf.lo -MD -MP -MF common/os/.deps/os_perf.Tpo -c common/os/os_perf.c  -fPIC -DPIC -o common/os/.libs/os_perf.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/os_perf.lo -MD -MP -MF common/os/.deps/os_perf.Tpo -c common/os/os_perf.c -o common/os/os_perf.o >/dev/null 2>&1
depbase=`echo common/os/os_util.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/os_util.lo -MD -MP -MF $depbase.Tpo -c -o common/os/os_util.lo common/os/os_util.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/os_util.lo -MD -MP -MF common/os/.deps/os_util.Tpo -c common/os/os_util.c  -fPIC -DPIC -o common/os/.libs/os_util.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/os_util.lo -MD -MP -MF common/os/.deps/os_util.Tpo -c common/os/os_util.c -o common/os/os_util.o >/dev/null 2>&1
depbase=`echo common/os/os_win.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/os_win.lo -MD -MP -MF $depbase.Tpo -c -o common/os/os_win.lo common/os/os_win.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/os_win.lo -MD -MP -MF common/os/.deps/os_win.Tpo -c common/os/os_win.c  -fPIC -DPIC -o common/os/.libs/os_win.o
common/os/os_win.c: In function ‘bufaddr_cmp’:
common/os/os_win.c:564:24: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  const uint64_t addr = (const uint64_t)p1;
                        ^
common/os/os_win.c: In function ‘llcallchain_bufinfo_show’:
common/os/os_win.c:624:22: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  if ((line = bsearch((void *)(dyn->addr), lat_buf, nlines,
                      ^
common/os/os_win.c: In function ‘os_lat_buf_hit’:
common/os/os_win.c:794:22: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  if ((line = bsearch((void *)(rec->addr), lat_buf, nlines,
                      ^
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/os_win.lo -MD -MP -MF common/os/.deps/os_win.Tpo -c common/os/os_win.c -o common/os/os_win.o >/dev/null 2>&1
depbase=`echo common/os/pfwrapper.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/pfwrapper.lo -MD -MP -MF $depbase.Tpo -c -o common/os/pfwrapper.lo common/os/pfwrapper.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/pfwrapper.lo -MD -MP -MF common/os/.deps/pfwrapper.Tpo -c common/os/pfwrapper.c  -fPIC -DPIC -o common/os/.libs/pfwrapper.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/pfwrapper.lo -MD -MP -MF common/os/.deps/pfwrapper.Tpo -c common/os/pfwrapper.c -o common/os/pfwrapper.o >/dev/null 2>&1
depbase=`echo common/os/plat.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/plat.lo -MD -MP -MF $depbase.Tpo -c -o common/os/plat.lo common/os/plat.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/plat.lo -MD -MP -MF common/os/.deps/plat.Tpo -c common/os/plat.c  -fPIC -DPIC -o common/os/.libs/plat.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/plat.lo -MD -MP -MF common/os/.deps/plat.Tpo -c common/os/plat.c -o common/os/plat.o >/dev/null 2>&1
depbase=`echo common/os/sym.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/sym.lo -MD -MP -MF $depbase.Tpo -c -o common/os/sym.lo common/os/sym.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/sym.lo -MD -MP -MF common/os/.deps/sym.Tpo -c common/os/sym.c  -fPIC -DPIC -o common/os/.libs/sym.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/os/sym.lo -MD -MP -MF common/os/.deps/sym.Tpo -c common/os/sym.c -o common/os/sym.o >/dev/null 2>&1
depbase=`echo common/cmd.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/cmd.lo -MD -MP -MF $depbase.Tpo -c -o common/cmd.lo common/cmd.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/cmd.lo -MD -MP -MF common/.deps/cmd.Tpo -c common/cmd.c  -fPIC -DPIC -o common/.libs/cmd.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/cmd.lo -MD -MP -MF common/.deps/cmd.Tpo -c common/cmd.c -o common/cmd.o >/dev/null 2>&1
depbase=`echo common/disp.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/disp.lo -MD -MP -MF $depbase.Tpo -c -o common/disp.lo common/disp.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/disp.lo -MD -MP -MF common/.deps/disp.Tpo -c common/disp.c  -fPIC -DPIC -o common/.libs/disp.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/disp.lo -MD -MP -MF common/.deps/disp.Tpo -c common/disp.c -o common/disp.o >/dev/null 2>&1
depbase=`echo common/lwp.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/lwp.lo -MD -MP -MF $depbase.Tpo -c -o common/lwp.lo common/lwp.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/lwp.lo -MD -MP -MF common/.deps/lwp.Tpo -c common/lwp.c  -fPIC -DPIC -o common/.libs/lwp.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/lwp.lo -MD -MP -MF common/.deps/lwp.Tpo -c common/lwp.c -o common/lwp.o >/dev/null 2>&1
depbase=`echo common/page.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/page.lo -MD -MP -MF $depbase.Tpo -c -o common/page.lo common/page.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/page.lo -MD -MP -MF common/.deps/page.Tpo -c common/page.c  -fPIC -DPIC -o common/.libs/page.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/page.lo -MD -MP -MF common/.deps/page.Tpo -c common/page.c -o common/page.o >/dev/null 2>&1
depbase=`echo common/perf.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/perf.lo -MD -MP -MF $depbase.Tpo -c -o common/perf.lo common/perf.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/perf.lo -MD -MP -MF common/.deps/perf.Tpo -c common/perf.c  -fPIC -DPIC -o common/.libs/perf.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/perf.lo -MD -MP -MF common/.deps/perf.Tpo -c common/perf.c -o common/perf.o >/dev/null 2>&1
depbase=`echo common/proc.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/proc.lo -MD -MP -MF $depbase.Tpo -c -o common/proc.lo common/proc.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/proc.lo -MD -MP -MF common/.deps/proc.Tpo -c common/proc.c  -fPIC -DPIC -o common/.libs/proc.o
common/proc.c: In function ‘proc_group_refresh’:
common/proc.c:749:10: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     j = ((uint64_t)p - (uint64_t)procs_new) /
          ^
common/proc.c:749:24: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     j = ((uint64_t)p - (uint64_t)procs_new) /
                        ^
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/proc.lo -MD -MP -MF common/.deps/proc.Tpo -c common/proc.c -o common/proc.o >/dev/null 2>&1
depbase=`echo common/reg.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/reg.lo -MD -MP -MF $depbase.Tpo -c -o common/reg.lo common/reg.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/reg.lo -MD -MP -MF common/.deps/reg.Tpo -c common/reg.c  -fPIC -DPIC -o common/.libs/reg.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/reg.lo -MD -MP -MF common/.deps/reg.Tpo -c common/reg.c -o common/reg.o >/dev/null 2>&1
depbase=`echo common/ui_perf_map.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/ui_perf_map.lo -MD -MP -MF $depbase.Tpo -c -o common/ui_perf_map.lo common/ui_perf_map.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/ui_perf_map.lo -MD -MP -MF common/.deps/ui_perf_map.Tpo -c common/ui_perf_map.c  -fPIC -DPIC -o common/.libs/ui_perf_map.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/ui_perf_map.lo -MD -MP -MF common/.deps/ui_perf_map.Tpo -c common/ui_perf_map.c -o common/ui_perf_map.o >/dev/null 2>&1
depbase=`echo common/util.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/util.lo -MD -MP -MF $depbase.Tpo -c -o common/util.lo common/util.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/util.lo -MD -MP -MF common/.deps/util.Tpo -c common/util.c  -fPIC -DPIC -o common/.libs/util.o
common/util.c: In function ‘msdiff’:
common/util.c:281:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if (sdiff >= (MAX_VALUE / MS_SEC)) {
            ^~
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/util.lo -MD -MP -MF common/.deps/util.Tpo -c common/util.c -o common/util.o >/dev/null 2>&1
depbase=`echo common/win.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/win.lo -MD -MP -MF $depbase.Tpo -c -o common/win.lo common/win.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/win.lo -MD -MP -MF common/.deps/win.Tpo -c common/win.c  -fPIC -DPIC -o common/.libs/win.o
common/win.c: In function ‘llrec2addr’:
common/win.c:2671:17: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   addr_buf[i] = (void *)(grp->rec_arr[i].addr);
                 ^
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2 -MT common/win.lo -MD -MP -MF common/.deps/win.Tpo -c common/win.c -o common/win.o >/dev/null 2>&1
/bin/bash ./libtool  --tag=CC   --mode=link gcc -fPIC -O2 -g -Wall -W -Wformat-security -D_FORTIFY_SOURCE=2 -fno-common -std=gnu99 -g -O2   -o libnumatop.la  common/os/map.lo common/os/node.lo common/os/os_cmd.lo common/os/os_page.lo common/os/os_perf.lo common/os/os_util.lo common/os/os_win.lo common/os/pfwrapper.lo common/os/plat.lo common/os/sym.lo common/cmd.lo common/disp.lo common/lwp.lo common/page.lo common/perf.lo common/proc.lo common/reg.lo common/ui_perf_map.lo common/util.lo common/win.lo    -lncurses -lpthread 
libtool: link: ar cru .libs/libnumatop.a common/os/.libs/map.o common/os/.libs/node.o common/os/.libs/os_cmd.o common/os/.libs/os_page.o common/os/.libs/os_perf.o common/os/.libs/os_util.o common/os/.libs/os_win.o common/os/.libs/pfwrapper.o common/os/.libs/plat.o common/os/.libs/sym.o common/.libs/cmd.o common/.libs/disp.o common/.libs/lwp.o common/.libs/page.o common/.libs/perf.o common/.libs/proc.o common/.libs/reg.o common/.libs/ui_perf_map.o common/.libs/util.o common/.libs/win.o 
ar: `u' modifier ignored since `D' is the default (see `U')
libtool: link: ranlib .libs/libnumatop.a
libtool: link: ( cd ".libs" && rm -f "libnumatop.la" && ln -s "../libnumatop.la" "libnumatop.la" )
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT common/numatop-numatop.o -MD -MP -MF common/.deps/numatop-numatop.Tpo -c -o common/numatop-numatop.o `test -f 'common/numatop.c' || echo './'`common/numatop.c
mv -f common/.deps/numatop-numatop.Tpo common/.deps/numatop-numatop.Po
/bin/bash ./libtool  --tag=CC   --mode=link gcc  -g -O2   -o numatop common/numatop-numatop.o libnumatop.la  -lncurses -lpthread 
libtool: link: gcc -g -O2 -o numatop common/numatop-numatop.o  ./.libs/libnumatop.a -lncurses -lpthread
common/numatop-numatop.o: In function `main':
/home/king/tmp/numatop/common/numatop.c:175: undefined reference to `plat_detect'
./.libs/libnumatop.a(map.o): In function `map_map2numa':
/home/king/tmp/numatop/common/os/map.c:367: undefined reference to `numa_move_pages'
./.libs/libnumatop.a(map.o): In function `map_addr2nodedst':
/home/king/tmp/numatop/common/os/map.c:393: undefined reference to `numa_move_pages'
./.libs/libnumatop.a(os_util.o): In function `calibrate_cpuinfo':
/home/king/tmp/numatop/common/os/os_util.c:173: undefined reference to `arch__cpuinfo_freq'
./.libs/libnumatop.a(os_util.o): In function `calibrate_by_tsc':
/home/king/tmp/numatop/common/os/os_util.c:259: undefined reference to `rdtsc'
/home/king/tmp/numatop/common/os/os_util.c:261: undefined reference to `rdtsc'
./.libs/libnumatop.a(pfwrapper.o): In function `profiling_sample_read':
/home/king/tmp/numatop/common/os/pfwrapper.c:344: undefined reference to `is_userspace'
./.libs/libnumatop.a(pfwrapper.o): In function `ll_sample_read':
/home/king/tmp/numatop/common/os/pfwrapper.c:539: undefined reference to `is_userspace'
./.libs/libnumatop.a(plat.o): In function `plat_profiling_config':
/home/king/tmp/numatop/common/os/plat.c:50: undefined reference to `s_plat_profiling_config'
./.libs/libnumatop.a(plat.o): In function `plat_ll_config':
/home/king/tmp/numatop/common/os/plat.c:64: undefined reference to `s_plat_ll_config'
./.libs/libnumatop.a(plat.o): In function `plat_offcore_num':
/home/king/tmp/numatop/common/os/plat.c:90: undefined reference to `s_plat_offcore_num'
./.libs/libnumatop.a(ui_perf_map.o): In function `get_ui_perf_count_map':
/home/king/tmp/numatop/common/ui_perf_map.c:40: undefined reference to `ui_perf_count_map'
collect2: error: ld returned 1 exit status
Makefile:901: recipe for target 'numatop' failed
make[1]: *** [numatop] Error 1
make[1]: Leaving directory '/home/king/tmp/numatop'
Makefile:665: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by ColinIanKing** [comment]
Bisected i386 build failure, bad commit is:

(artful-i386)king@sharkbay:~/tmp/numatop$ git bisect bad
47863edc15672cab4c4f5da1d5d28d894ad4e493 is the first bad commit
commit 47863edc15672cab4c4f5da1d5d28d894ad4e493
Author: Auke Kok <auke-jan.h.kok@intel.com>
Date:   Wed May 2 16:24:23 2018 -0700

    Convert to autotools.
    
    - Rename README to README.md and use markdown support.
    - Update gitignore
    - uses `autogen.sh` for git tree builds
    - passes `make distcheck`

**Comment by ColinIanKing** [comment]
AM_CONDITIONAL(CPU_INTEL, test "x$host_cpu" = "xi686") is required in configure.ac - I've sent fix for this.

**Comment by yaoj** [comment]
Applied. Thanks for fixing on 32 bit platform.

**Comment by ColinIanKing** [comment]
Hi there,

Oops, seems that my "fix" breaks things for x86-64 64 bit. I suspect the
same broken logic needs fixing for CPU_PPC

Colin
